name: Spotless

on:
  push:
    branches:
      - main
      - master
      - Grzegorz

jobs:
  spotless:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'openjdk@1.21'
          java-version: '21'

      - name: Run Spotless
        run: ./gradlew spotlessApply