name: Spotless

on:
  push:
    branches:
      - main
      - master
      - Grzegorz

jobs:
  spotless:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 21 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install Maven
        run: sudo apt-get install maven

      - name: Run Spotless
        run: mvn spotless:apply
